#! /bin/bash

sdd_install() {
    local version=$1
    local package=bat-$version-x86_64-unknown-linux-musl

    wget -P /tmp https://github.com/sharkdp/bat/releases/download/$version/$package.tar.gz
    cd /tmp
    tar xf $package.tar.gz

    mv $package/bat "$SDD_INSTALL_PREFIX"/bin

    # Install man page
    mkdir -p "$SDD_INSTALL_PREFIX"/share/man/man1
    mv $package/bat.1 "$SDD_INSTALL_PREFIX"/share/man/man1

    rm -rf $package.tar.gz $package
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX"/bin/bat
    rm -f "$SDD_INSTALL_PREFIX"/share/man/man1/bat.1
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release sharkdp bat
}
