#! /bin/bash

sdd_install() {
    local version=$1
    local package=bat-$version-x86_64-unknown-linux-gnu

    wget -P /tmp https://github.com/sharkdp/bat/releases/download/$version/$package.tar.gz
    cd /tmp
    tar xf $package.tar.gz

    mv $package/bat "$SDD_INSTALL_PREFIX"/bin

    # Install man page
    mkdir -p "$SDD_INSTALL_PREFIX"/share/man/man1
    mv $package/bat.1 "$SDD_INSTALL_PREFIX"/share/man/man1

    rm -rf $package.tar.gz $package
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX"/bin/bat
    rm -f "$SDD_INSTALL_PREFIX"/share/man/man1/bat.1
}

foo() {
    # https://github.com/sharkdp/bat/issues/34#issuecomment-385634632
    # Get theme
    mkdir -p ~/.config/bat/themes
    cd ~/.config/bat/themes
    git clone https://github.com/braver/Solarized
    ln -sf "Solarized/Solarized (dark).tmTheme" Default.tmTheme

    # Get language definition files
    mkdir -p ~/.config/bat/syntaxes
    cd ~/.config/bat/syntaxes
    git clone https://github.com/sublimehq/Packages/
    rm -rf Packages/Markdown
    git clone https://github.com/jonschlinkert/sublime-markdown-extended
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release sharkdp bat
}
