#!/usr/bin/env bash

sdd_install() {
    local version=$1
    wget -O "$SDD_INSTALL_PREFIX/bin/borg" https://github.com/borgbackup/borg/releases/download/"$version"/borg-linux64
    chmod u+x "$SDD_INSTALL_PREFIX/bin/borg"
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX/bin/borg"
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release borgbackup borg
}
