#!/usr/bin/env bash

sdd_install() {
    local version=$1
    wget -O "$SDD_INSTALL_PREFIX/bin/broot" https://github.com/Canop/broot/releases/download/$version/broot
    chmod u+x "$SDD_INSTALL_PREFIX/bin/broot"
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX/bin/broot"
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release Canop broot
}
