#!/usr/bin/env bash

sdd_install() {
    local version=$1
    wget -O "$SDD_INSTALL_PREFIX/bin/dasel" https://github.com/TomWright/dasel/releases/download/$version/dasel_linux_amd64
    chmod u+x "$SDD_INSTALL_PREFIX/bin/dasel"
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX/bin/dasel"
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release TomWright dasel
}
