#!/usr/bin/env bash

sdd_install() {
    local version=$1
    wget -O "$SDD_INSTALL_PREFIX/bin/diff-so-fancy" https://raw.githubusercontent.com/so-fancy/diff-so-fancy/$version/third_party/build_fatpack/diff-so-fancy
    chmod u+x "$SDD_INSTALL_PREFIX/bin/diff-so-fancy"
    # git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX/bin/diff-so-fancy"
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release so-fancy diff-so-fancy
}
