#!/usr/bin/env bash

sdd_install() {
    local version=$1
    wget -O "$SDD_INSTALL_PREFIX/bin/direnv" https://github.com/direnv/direnv/releases/download/$version/direnv.linux-amd64
    chmod u+x "$SDD_INSTALL_PREFIX/bin/direnv"

    # Install man page
    mkdir -p "$SDD_INSTALL_PREFIX"/share/man/man1
    wget -O "$SDD_INSTALL_PREFIX"/share/man/man1/direnv.1 https://raw.githubusercontent.com/direnv/direnv/$version/man/direnv.1
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX/bin/direnv"
    rm -f "$SDD_INSTALL_PREFIX"/share/man/man1/direnv.1
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release direnv direnv
}
