#! /bin/bash

sdd_install() {
    local version=$1
    local package=dust-$version-x86_64-unknown-linux-musl

    wget -P /tmp https://github.com/bootandy/dust/releases/download/$version/$package.tar.gz
    cd /tmp
    tar xf $package.tar.gz

    mv $package/dust "$SDD_INSTALL_PREFIX"/bin

    rm -rf $package.tar.gz $package
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX"/bin/dust
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release bootandy dust
}
