#!/usr/bin/env bash

sdd_install() {
    local version=$1
    local archive=go$version.linux-amd64.tar.gz
    echo $version
    echo $archive

    wget -P /tmp https://dl.google.com/go/"$archive"
    cd /tmp || return 1
    tar xfv "$archive"
    mv go "$SDD_INSTALL_PREFIX"

    rm -rfv "$archive"
}

sdd_uninstall() {
    rm -rvf "$SDD_INSTALL_PREFIX"/go
}

sdd_fetch_latest_version() {
    # hard-coding since I can't find an API to query the latest version
    echo 1.15.5
}
