#!/bin/bash

sdd_install() {
    local version=$1
    local arch=amd64
    if [[ $(arch) = armv7l ]]; then
        arch=arm
    fi

    # Strip prefixed v from version number for package name
    local package=hub-linux-$arch-$(echo $version | tr -d v)

    wget -P /tmp https://github.com/github/hub/releases/download/$version/$package.tgz
    cd /tmp
    tar xf $package.tgz

    PREFIX="$SDD_INSTALL_PREFIX" $package/install

    cp $package/etc/hub.zsh_completion "$SDD_ZSH_COMPLETION_DIR"/_hub

    rm -rf $package $package.tgz
}

sdd_uninstall() {
    rm -rf "$SDD_INSTALL_PREFIX"/bin/hub
    rm -rf "$SDD_INSTALL_PREFIX"/share/vim/**/pullrequest.vim
    rm -rf "$SDD_INSTALL_PREFIX"/share/man/man1/hub*
    rm -rf "$SDD_ZSH_COMPLETION_DIR"/_hub
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release github hub
}
