#!/usr/bin/env bash

sdd_install() {
    local version=$1
    wget -O "$SDD_INSTALL_PREFIX/bin/jq" https://github.com/jqlang/jq/releases/download/"$version"/jq-linux64
    chmod u+x "$SDD_INSTALL_PREFIX/bin/jq"

    mkdir -p "$SDD_INSTALL_PREFIX"/share/man/man1
    wget -O "$SDD_INSTALL_PREFIX"/share/man/man1/jq.1 https://raw.githubusercontent.com/jqlang/jq/refs/tags/"$version"/jq.1.prebuilt
}

sdd_uninstall() {
    rm -rfv "$SDD_INSTALL_PREFIX/bin/jq"
    rm -rfv "$SDD_INSTALL_PREFIX/share/man/man1/jq.1"
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release jqlang jq
}
