#!/usr/bin/env bash

sdd_install() {
    local version=$1
    wget -O "$SDD_INSTALL_PREFIX/bin/jq" https://github.com/stedolan/jq/releases/download/$version/jq-linux64
    chmod u+x "$SDD_INSTALL_PREFIX/bin/jq"
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX/bin/jq"
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release stedolan jq
}
