#!/usr/bin/env bash

sdd_install() {
    local version=$1
    local archive
    if [[ $version = 1.* ]]; then
        archive=ncdu-linux-x86_64-"$version".tar.gz
    else
        archive=ncdu-"$version"-linux-x86_64.tar.gz
    fi
    wget -P /tmp https://dev.yorhel.nl/download/"$archive"

    cd /tmp || return 1
    tar xfv "$archive"
    mv ncdu "$SDD_INSTALL_PREFIX"/bin
    rm "$archive"
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX"/bin/ncdu
}

sdd_fetch_latest_version() {
    echo 2.0
}
