#! /bin/bash

sdd_install() {
    command -v python3 >/dev/null 2>&1 || return 1

    if [[ $(python3 --version) = "Python 3.5."* ]]; then
        wget -P /tmp https://bootstrap.pypa.io/pip/3.5/get-pip.py
    else
        wget -P /tmp https://bootstrap.pypa.io/get-pip.py
    fi
    python3 /tmp/get-pip.py --user
    sdd_upgrade "$1"

    ~/.local/bin/pip completion --bash > "$SDD_BASH_COMPLETION_DIR"/pip
    ~/.local/bin/pip completion --zsh > "$SDD_ZSH_COMPLETION_DIR"/_pip

    rm /tmp/get-pip.py
}

sdd_upgrade() {
    ~/.local/bin/pip install --user --upgrade pip=="$1"
}

sdd_uninstall() {
    ~/.local/bin/pip uninstall --yes pip
    rm -rvf "$SDD_BASH_COMPLETION_DIR"/pip "$SDD_ZSH_COMPLETION_DIR"/_pip
}

sdd_fetch_latest_version() {
    _name_of_latest_github_tag pypa pip
}
