#!/usr/bin/env bash

QMLFMT_TARFILE=qmlfmt.tar.gz

sdd_install() {
    local version=$1
    wget -P /tmp https://github.com/jesperhh/qmlfmt/releases/download/$version/$QMLFMT_TARFILE
    tar xf /tmp/$QMLFMT_TARFILE

    mv /tmp/qmlfmt $SDD_INSTALL_PREFIX/bin

    rm /tmp/$QMLFMT_TARFILE
}

sdd_fetch_latest_version() {
    wget -qO- https://api.github.com/repos/jesperhh/qmlfmt/releases/latest | grep tag_name | awk '{ print $2; }' | sed 's/[",]//g'
}
