#!/usr/bin/env bash

QMLFMT_VERSION=1.0.71
QMLFMT_TARFILE=qmlfmt.tar.gz

sdd_install() {
    wget -P /tmp https://github.com/jesperhh/qmlfmt/releases/download/$QMLFMT_VERSION/$QMLFMT_TARFILE
    tar xf /tmp/$QMLFMT_TARFILE

    mv /tmp/qmlfmt $SDD_INSTALL_PREFIX/bin

    rm /tmp/$QMLFMT_TARFILE
}
