#!/usr/bin/env bash

sdd_install() {
    local version=$1
    local arch=x86_64
    local suffix=musl

    if [[ $(arch) = arm* ]]; then
        arch=arm
        suffix=gnueabihf
    fi

    local package=ripgrep-$version-$arch-unknown-linux-$suffix

    wget -P /tmp https://github.com/BurntSushi/ripgrep/releases/download/$version/$package.tar.gz
    cd /tmp
    tar xf $package.tar.gz

    # Install binary
    mv $package/rg "$SDD_INSTALL_PREFIX"/bin

    mv $package/complete/rg.bash "$SDD_BASH_COMPLETION_DIR"/rg
    mv $package/complete/_rg "$SDD_ZSH_COMPLETION_DIR"

    # Install man page
    mkdir -p "$SDD_INSTALL_PREFIX"/share/man/man1
    mv $package/doc/rg.1 "$SDD_INSTALL_PREFIX"/share/man/man1

    rm -rf $package.tar.gz $package
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX"/bin/rg
    rm -f "$SDD_BASH_COMPLETION_DIR"/rg
    rm -f "$SDD_ZSH_COMPLETION_DIR"/_rg
    rm -f "$SDD_INSTALL_PREFIX"/share/man/man1/rg.1
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release BurntSushi ripgrep
}
