#!/usr/bin/env bash

sdd_install() {
    local version=$1
    local arch=$(arch)
    local suffix=musl

    if [[ $arch = *arm ]]; then
        arch=arm
        suffix=gnueabihf
    fi

    local package=ripgrep-$version-$arch-unknown-linux-$suffix

    wget -P /tmp https://github.com/BurntSushi/ripgrep/releases/download/$version/$package.tar.gz
    cd /tmp
    tar xf $package.tar.gz

    # Install binary
    mv $package/rg "$SDD_INSTALL_PREFIX"/bin

    # Install zsh completion
    mkdir -p  "$SDD_INSTALL_PREFIX"/share/zsh/site-functions
    mv $package/complete/_rg "$SDD_INSTALL_PREFIX"/share/zsh/site-functions

    # Install man page
    mkdir -p "$SDD_INSTALL_PREFIX"/share/man/man1
    mv $package/doc/rg.1 "$SDD_INSTALL_PREFIX"/share/man/man1

    rm -rf $package.tar.gz $package
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX"/bin/rg
    rm -f "$SDD_INSTALL_PREFIX"/share/zsh/site-functions/_rg
    rm -f "$SDD_INSTALL_PREFIX"/share/man/man1/rg.1
}

sdd_fetch_latest_version() {
    wget -qO- https://api.github.com/repos/BurntSushi/ripgrep/releases/latest | grep tag_name | awk '{ print $2; }' | sed 's/[",]//g'
}
