#!/usr/bin/env bash

sdd_install() {
    git clone https://github.com/pylipp/sdd /tmp/sdd
    /tmp/sdd/bootstrap.sh
    rm -rf /tmp/sdd
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX/bin/sdd"
    rm -rf "$SDD_INSTALL_PREFIX/lib/sdd"
}
