#!/usr/bin/env bash

sdd_install() {
    local version=$1
    git clone https://github.com/pylipp/sdd /tmp/sdd
    cd /tmp/sdd
    git checkout $version >/dev/null
    ./bootstrap.sh
    cd ..
    rm -rf sdd
}

sdd_upgrade() {
    sdd_install "$1"
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX/bin/sdd"
    rm -rf "$SDD_INSTALL_PREFIX/lib/sdd"
}

sdd_fetch_latest_version() {
    _sha_of_github_master pylipp sdd
}
