#! /bin/bash

sdd_install() {
    local version=$1
    local package=shellcheck-$version
    local archive=$package.linux.x86_64.tar.xz

    wget -P /tmp https://shellcheck.storage.googleapis.com/$archive
    cd /tmp
    tar xf $archive

    mv $package/shellcheck "$SDD_INSTALL_PREFIX"/bin

    rm -rf $archive $package
}

sdd_uninstall() {
    rm -v "$SDD_INSTALL_PREFIX"/bin/shellcheck
}

sdd_fetch_latest_version() {
    _name_of_latest_github_tag koalaman shellcheck
}
