#!/usr/bin/env bash

sdd_install() {
    local version=$1
    wget -O "$SDD_INSTALL_PREFIX/bin/shfmt" https://github.com/mvdan/sh/releases/download/"$version/shfmt_$version"_linux_amd64
    chmod u+x "$SDD_INSTALL_PREFIX/bin/shfmt"
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX/bin/shfmt"
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release mvdan sh
}
