#!/usr/bin/env bash

sdd_install() {
    local version="$1"
    wget -O "$SDD_INSTALL_PREFIX"/bin/wuzz https://github.com/stedolan/wuzz/releases/download/"$version"/wuzz_linux_amd64
    chmod u+x "$SDD_INSTALL_PREFIX"/bin/wuzz
}

sdd_uninstall() {
    rm -f "$SDD_INSTALL_PREFIX"/bin/wuzz
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release asciimoo wuzz
}
