#!/usr/bin/env bash

sdd_install() {
    local version=$1
    local package=xan-x86_64-unknown-linux-musl
    local archive="$package".tar.gz
    wget -P /tmp https://github.com/medialab/xan/releases/download/"$version"/"$archive"

    cd /tmp || return 1
    tar xfv "$archive"
    mv xan "$SDD_INSTALL_PREFIX"/bin/xan
    "$SDD_INSTALL_PREFIX"/bin/xan completions bash > "$SDD_BASH_COMPLETION_DIR"/xan
    "$SDD_INSTALL_PREFIX"/bin/xan completion zsh > "$SDD_ZSH_COMPLETION_DIR"/_xan
    rm -rfv "$archive"
}

sdd_uninstall() {
    rm -fv "$SDD_INSTALL_PREFIX"/bin/xan
    rm -fv "$SDD_BASH_COMPLETION_DIR"/xan
    rm -fv "$SDD_ZSH_COMPLETION_DIR"/_xan
}

sdd_fetch_latest_version() {
    _tag_name_of_latest_github_release medialab xan
}
