#!/usr/bin/env bash

set -e

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
VENV_DIR=~/.virtualenvs/sdd

python3 -m venv "$VENV_DIR"
# shellcheck disable=SC1090
source "$VENV_DIR"/bin/activate
pip install -U -r "$SCRIPTDIR"/requirements.txt
pre-commit install -f
